# https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu
- name: Install Git LFS
  become: true
  ansible.builtin.apt:
    name: git-lfs
    state: latest
    update_cache: true

# ref: https://github.com/ansible/ansible-lint/issues/1780
- name: Check if git lfs is installed # https://github.com/git-lfs/git-lfs/issues/901
  community.general.git_config:
    list_all: true
    scope: global
  register: git_lfs__git_global_config

- name: Setup Git LFS
  ansible.builtin.command: git lfs install
  when: "'filter.lfs.required' not in git_lfs__git_global_config.config_values"
  changed_when: true

- name: Install pre-commit
  ansible.builtin.pip:
    name: pre-commit
    state: latest
    executable: pip3

- name: Install clang-format
  ansible.builtin.pip:
    name: clang-format
    version: "{{ pre_commit_clang_format_version }}"
    executable: pip3

- name: Install Go
  become: true
  ansible.builtin.apt:
    name: golang
    state: latest
    update_cache: true

- name: Install plotjuggler
  become: true
  ansible.builtin.apt:
    name:
      - ros-{{ rosdistro }}-plotjuggler-ros
    state: latest
    update_cache: true
