- name: Install libqt5charts5-dev # remove this task after merging https://github.com/ros/rosdistro/pull/39705.
  become: true
  ansible.builtin.apt:
    name: libqt5charts5-dev
    state: latest
    update_cache: true

- name: Install geographiclib-tools
  become: true
  ansible.builtin.apt:
    name: geographiclib-tools
    state: latest
    update_cache: true

- name: Install egm2008-1
  become: true
  ansible.builtin.command:
    cmd: geographiclib-get-geoids egm2008-1
    creates: /usr/share/GeographicLib/geoids/egm2008-1.pgm
